### ISSUE TITLE
Training failed

### ISSUE THREAD

**Issue by susheelsk** [ragulin/face-recognition-server#2]
When i set up the system and then load localhost:8888 on the broser, the page opens and it notifies me saying it doesn't recognize me. So i enter my name and click ok. I get a few exceptions caught in the terminal. 

The error is in the line gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY) //opencv.py", line 23. 
The directory is created but there is no images in the directory in the images folder. 

Please look into this matter

**Comment by ragulin** [comment]
Updated the README with further instructions. The file 'haarcascade_frontalface_alt.xml' needs to be copied from /data/haarcascades/ to the data directory.

Also updated opencv.py to use cv2.CASCADE_SCALE_IMAGE instead of cv2.cv.CV_HAAR_SCALE_IMAGE. Hopefullt this will solve the issue.

**Comment by goyal71** [comment]
getting a similar issue
