### ISSUE TITLE
Socket Connection Closed

### ISSUE THREAD

**Issue by all3nT** [ragulin/face-recognition-server#7]
I am not sure if this is an issue with my install or not but my server is unable to access ws://localhost:8888/predict. It looks like there is no socket server listening. Do you know what I may have missed or how to fix this? From what I have read it looks like Tornado is handling the sockets.

From Google Chrome's error console

```
WebSocket connection to 'ws://localhost:8888/predict' failed: Connection closed before receiving a handshake response 
```

I am also seeing this in the console

```
WebSocket is already in CLOSING or CLOSED state. 
```

**Comment by all3nT** [comment]
I resolved the issue be re installing tornado.

**Comment by goyal71** [comment]
i am having this similar issue... i am using ubuntu 14.04 ..   tried reinstalling it but still there is error

**Comment by all3nT** [comment]
Try reinstalling the opencv python bindings. I think the error it is getting in the predict handler might be from opencv. You can also try uninstalling and reinstalling tornado.

**Comment by goyal71** [comment]
i  already tried that ... i saw the server log 
i am getting error " gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    TypeError: src data type = 17 is not supported
"
any idea?

**Comment by all3nT** [comment]
That seems like there is an issue with the image type that is being sent. I am not sure how to fix this but this might help,  [http://stackoverflow.com/questions/11642178/data-type-errors-for-input-images-of-cv2-calcopticalflowpyrlk](http://stackoverflow.com/questions/11642178/data-type-errors-for-input-images-of-cv2-calcopticalflowpyrlk). I think I remember getting an error like this at some point but I believe I just re installed the packaged to fix the problem.
