### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'save'

### ISSUE THREAD

**Issue by lcsbonilla** [ragulin/face-recognition-server#9]
In the function called `load_images_to_db(path):` I receive an error message as follow above:

```
in load_images_to_db  label.save()
AttributeError: 'tuple' object has no attribute 'save'
```

Can anyone help me?

**Comment by lcsbonilla** [comment]
I made by myself.
The problem was in the returned method.
get_or_create() returns a tuple wich the second term is a boolean.

I just put another variable to get a split information...

**Comment by maazashraf23** [comment]
> I made by myself.
> The problem was in the returned method.
> get_or_create() returns a tuple wich the second term is a boolean.
> 
> I just put another variable to get a split information...

can you tell me in detail how you manage to solve it. i have the same problem while saving the photos of my labelled data.

**Comment by ghost** [comment]
I'd be very much interested in that solution too!
